### PR TITLE
fix: 检查驱动接口存在安全漏洞

### PR DESCRIPTION
**Pull request by wyu71**
添加检查驱动接口限制

Log: 添加检查驱动接口限制
/review @lzwind @jeffshuai @feeengli @pengfeixx @HeeMingYang @myk1343

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
