### PR TITLE
fix: 在系统下设备管理器中网络适配器中未显示板载有线网卡信息

### PR DESCRIPTION
**Pull request by wyu71**
HW Address和Permanent HW Address不一致导致lshw网卡匹配失败

Log: 正确显示网卡信息
Bug: https://pms.uniontech.com/bug-view-189671.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
