### PR TITLE
fix: 插入新设备点击重新检测按钮扫描无法识别

### PR DESCRIPTION
**Pull request by wyu71**
扫描驱动前先扫描设备

Log: 正常识别驱动
Bug: https://pms.uniontech.com/bug-view-131857.html
/review @lzwind @feeengli @hundundadi @myk1343

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
