### PR TITLE
fix: 待机后不能通过PS2鼠标唤醒

### PR DESCRIPTION
**Pull request by feeengli**
修复待机后不能通过PS2鼠标唤醒

Log: 修复待机后不能通过PS2鼠标唤醒

Bug: https://pms.uniontech.com/bug-view-219597.html

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
