### PR TITLE
fix: USB外接网络适配器的制造商无法获取

### PR DESCRIPTION
**Pull request by wyu71**
通过lsusb获取USB外接网络适配器

Log: 正确显示USB外接网络适配器的制造商
Bug: https://pms.uniontech.com/bug-view-162141.html
/review @pengfeixx @jeffshuai @myk1343 @feeengli @HeeMingYang

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
