### PR TITLE
fix: 设备网络信息显示不全

### PR DESCRIPTION
**Pull request by wyu71**
启动时重新刷新设备信息

Log: 设备网络信息显示
/review @lzwind @jeffshuai @feeengli @hundundadi @myk1343 @pengfeixx

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
