### PR TITLE
fix: 列表内容较多时的间距问题

### PR DESCRIPTION
**Pull request by wyu71**
增加列表底部高度

Log: 正常显示列表内容较多的间距
Bug: https://pms.uniontech.com/bug-view-157701.html
/review @lzwind @jeffshuai @feeengli @pengfeixx

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
