### PR TITLE
fix: merge disk size unit error

### PR DESCRIPTION
**Pull request by jeffshuai**
merge disk size unit error

Log:  merge disk size unit error

Bug: https://pms.uniontech.com/bug-view-211013.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
