### PR TITLE
fix: 修复部分显示设备中当前分辨率信息与实际设置的不符

### PR DESCRIPTION
**Pull request by jeffshuai**
修复部分显示设备中当前分辨率信息与实际设置的不符

Log: 修复部分显示设备中当前分辨率信息与实际设置的不符

Bug: https://pms.uniontech.com/bug-view-204349.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
+1

**Pull request merged**
