### PR TITLE
feat: 读取设备管理器UFS 3.1

### PR DESCRIPTION
**Pull request by wyu71**
增加读取UFS 3.1信息

Log: 正确显示UFS 3.1信息
Task: https://pms.uniontech.com/task-view-219097.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — COMMENTED** [review]
/+1

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
