### PR TITLE
fix: N卡名称错误

### PR DESCRIPTION
**Pull request by wyu71**
添加读取N卡名称

Log: 显示N卡名称
/review @lzwind @feeengli @myk1343 @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
