### PR TITLE
fix: 无网络适配器模块

### PR DESCRIPTION
**Pull request by wyu71**
去除不正确的过滤方式

Log: 正确显示网络模块
Bug: https://pms.uniontech.com/bug-view-187583.html,https://pms.uniontech.com/bug-view-187585.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
