### PR TITLE
fix: 修复热拔插识别显示设备

### PR DESCRIPTION
**Pull request by jeffshuai**
修复热拔插识别显示设备

Log: 修复热拔插识别显示设备

Bug: https://pms.uniontech.com/bug-view-234593.html

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Comment by myk1343** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
