### PR TITLE
fix: hw声卡厂商和型号未显示

### PR DESCRIPTION
**Pull request by wyu71**
添加声卡厂商和型号

Log: 正确显示声卡厂商和型号
/review @lzwind @myk1343 @pengfeixx @feeengli @hundundadi @jeffshuai

### CODE REVIEW

**Review by HeeMingYang — APPROVED** [review]
/+1

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Pull request merged**
