### PR TITLE
fix: 修复备份还原过程中状态、信息未及时刷新问题

### PR DESCRIPTION
**Pull request by feeengli**
修复备份还原过程中状态、信息未及时刷新问题

Log: 修复备份还原过程中状态、信息未及时刷新问题

Bug: https://pms.uniontech.com/bug-view-226295.html
     https://pms.uniontech.com/bug-view-226323.html
     https://pms.uniontech.com/bug-view-226377.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
