### PR TITLE
fix: 未限制apt安装驱动

### PR DESCRIPTION
**Pull request by wyu71**
限制apt安装驱动

Log: 限制apt安装驱动
@lzwind @feeengli @myk1343 @hundundadi

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
