### PR TITLE
fix: gpu名称错误

### PR DESCRIPTION
**Pull request by wyu71**
修改获取GPU名称规则

Log: 正确显示GPU名称
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by hundundadi** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
