### PR TITLE
fix: 设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息

### PR DESCRIPTION
**Pull request by jeffshuai**
设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息

Log: 设备管理器M900-1050-update3-arm64-20230216-1644无GPU信息

Bug: https://pms.uniontech.com/bug-view-187791.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
