### PR TITLE
fix: 修复DeviceControl缓冲区溢出漏洞

### PR DESCRIPTION
**Pull request by jeffshuai**
修复DeviceControl缓冲区溢出漏洞

Log: 修复DeviceControl缓冲区溢出漏洞

Bug: https://pms.uniontech.com/bug-view-233127.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Comment by feeengli** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
