### PR TITLE
fix: 备份还原bug修复

### PR DESCRIPTION
**Pull request by feeengli**
修复备份/还原失败无法调起反馈弹窗，驱动还原界面可以扫描出当前备份版本，升级后无法继续备份问题；
备份/还原时置灰重新检测按钮；
UI问题修复。

Log: 修复备份/还原相关bug

Bug: https://pms.uniontech.com/bug-view-222339.html
     https://pms.uniontech.com/bug-view-222363.html
     https://pms.uniontech.com/bug-view-222379.html
     https://pms.uniontech.com/bug-view-222503.html
     https://pms.uniontech.com/bug-view-222513.html
     https://pms.uniontech.com/bug-view-222541.html
     https://pms.uniontech.com/bug-view-222567.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
