### PR TITLE
feat: 取消开机驱动安装提示

### PR DESCRIPTION
**Pull request by wyu71**
取消开机驱动安装提示

Log: 取消开机驱动安装提示
Task: https://pms.uniontech.com/story-view-18351.html
/review @pengfeixx @feeengli

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A
+1

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
