### PR TITLE
fix: 图形设备中制造商实际显示信息与预期显示信息不符

### PR DESCRIPTION
**Pull request by wyu71**
去掉图形设备中制造商

Log: 去掉图形设备中制造商
Bug: https://pms.uniontech.com/bug-view-151715.html
/review @pengfeixx @feeengli @jeffshuai @hundundadi

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A
+1

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
