### PR TITLE
fix: 仓库未更新时无法备份驱动

### PR DESCRIPTION
**Pull request by feeengli**
修复仓库未更新时无法下载驱动进行备份

Log: 修复仓库未更新时无法下载驱动进行备份

https://pms.uniontech.com/bug-view-242971.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — DISMISSED** [review]
/+1

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
