### PR TITLE
fix: 添加服务的读取设备时间

### PR DESCRIPTION
**Pull request by wyu71**
### 添加服务的读取设备时间

Log: 添加服务的读取设备时间
/review @lzwind @feeengli @hundundadi @myk1343 @HeeMingYang

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
