### PR TITLE
fix: 修复某些型号U盘不认识

### PR DESCRIPTION
**Pull request by jeffshuai**
修复某些型号U盘不认识

Log: 修复某些型号U盘不认识

Bug: https://pms.uniontech.com/bug-view-211371.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
