### PR TITLE
fix: 音频硬件设备信息制造商和型号信息重复显示

### PR DESCRIPTION
**Pull request by wyu71**
去除重复的制造商和型号信息

Log: 正常显示音频硬件设备信息
Bug: https://pms.uniontech.com/bug-view-153955.html
/review @lzwind @feeengli @hundundadi @myk1343

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
