### PR TITLE
fix:  修改Configgured Speed显示中文翻译

### PR DESCRIPTION
**Pull request by jeffshuai**
Configgured Speed显示英文

Log:  Configgured Speed显示中文

Bug: https://pms.uniontech.com/bug-view-252641.html

### CODE REVIEW

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
