### PR TITLE
chore: 更新翻译文件

### PR DESCRIPTION
**Pull request by wyu71**
更新翻译文件

Log: 更新翻译文件
/review @lzwind @pengfeixx @jeffshuai @HeeMingYang @feeengli @hualet @myk1343

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
