### PR TITLE
fix: 设备管理器只有概况信息

### PR DESCRIPTION
**Pull request by wyu71**
延迟网络加载驱动信息

Log: 正常显示设备信息
Bug: https://pms.uniontech.com/bug-view-146857.html
/review @lzwind @myk1343 @feeengli @jeffshuai @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
