### PR TITLE
fix: 设备管理器中内存单位与终端中输入dmidecode17查询的内存速率单位不符合

### PR DESCRIPTION
**Pull request by wyu71**
将dmidecode17查询的内存速率替换lshw信息

Log: 正确显示内存速率
Bug: https://pms.uniontech.com/bug-view-169555.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
