### PR TITLE
feat: add the userGuideLine for toml solution

### PR DESCRIPTION
**Pull request by jeffshuai**
add the userGuideLine for toml solution

Log: add the userGuideLine for toml solution

### CODE REVIEW

**Comment by feeengli** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
