### PR TITLE
fix: M900问题修复

### PR DESCRIPTION
**Pull request by jeffshuai**
M900问题修复

Log: M900问题修复

Bug: https://pms.uniontech.com/bug-view-221883.html
Bug: https://pms.uniontech.com/bug-view-187791.html
Bug: https://pms.uniontech.com/bug-view-207245.html
Bug: https://pms.uniontech.com/bug-view-207187.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
