### PR TITLE
fix: 显卡声卡网卡的时钟频率和位宽错误

### PR DESCRIPTION
**Pull request by wyu71**
隐藏显卡声卡网卡的PCI时钟频率和位宽

Log: 隐藏显卡声卡网卡的时钟频率和位宽
Bug: https://pms.uniontech.com/bug-view-160181.html,https://pms.uniontech.com/bug-view-159585.html
/review @pengfeixx @feeengli @jeffshuai @HeeMingYang

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Pull request merged**
