### PR TITLE
fix: 侧边栏hover/高亮时背景底没有与侧边栏居中对齐

### PR DESCRIPTION
**Pull request by wyu71**
侧边栏边距设置为11像素

Log: 居中显示侧边栏内容
Bug: https://pms.uniontech.com/bug-view-157697.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
