### PR TITLE
fix: 更新驱动弹窗提示词不居中

### PR DESCRIPTION
**Pull request by wyu71**
隐藏提示标签

Log: 更新驱动弹窗居中提示词
Bug: https://pms.uniontech.com/bug-view-157703.html
/review @lzwind @pengfeixx @jeffshuai @feeengli @myk1343 @HeeMingYang

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
