### PR TITLE
fix: 鼠标详情页面右键禁用且重新拔插鼠标之后鼠标能正常使用

### PR DESCRIPTION
**Pull request by wyu71**
重新计算Unique ID作为key值

Log: 正常禁用设备
Bug: https://pms.uniontech.com/bug-view-164801.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
