### PR TITLE
fix: cover the shutdown and exit may fail sometimes

### PR DESCRIPTION
**Pull request by jeffshuai**
cover the shutdown and exit may fail sometimes

Log: cover the shutdown and exit may fail sometimes

Bug: https://pms.uniontech.com/bug-view-200233.html

### CODE REVIEW

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
