### PR TITLE
fix: 通过宏判断是否打开驱动模块

### PR DESCRIPTION
**Pull request by feeengli**
驱动模块开关控制，部分情况不显示驱动模块

Log: 驱动模块开关控制

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
