### PR TITLE
feat: 设备管理器华为W585适配net

### PR DESCRIPTION
**Pull request by jeffshuai**
设备管理器华为W585适配net

Log:  设备管理器华为W585适配net

Task: https://pms.uniontech.com/task-view-264947.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by feeengli** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
