### PR TITLE
fix: 英伟达显卡设备管理器中无显存显示

### PR DESCRIPTION
**Pull request by wyu71**
通过smi读取显卡显存

Log: 正常显示显卡显存
Bug: https://pms.uniontech.com/bug-view-151025.html
/review @lzwind @feeengli @myk1343 @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
