### PR TITLE
fix: 修复部分网址设备识别问题

### PR DESCRIPTION
**Pull request by jeffshuai**
en01与en02网口MAC相同导致信息识别不全

Log: 网口的信息识别全

Bug: https://pms.uniontech.com/bug-view-230087.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
