### PR TITLE
fix: 设备管理器未正确获取处理器当前实时频率

### PR DESCRIPTION
**Pull request by wyu71**
去掉处理器当前实时频率显示

Log: 去掉处理器当前实时频率显示
Bug: https://pms.uniontech.com/bug-view-143719.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by jeffshuai** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
